-- Generated by scripts/generate-d1-seed.mjs.
-- This seeds D1 from src/data/tasks.json and src/data/weekly-reports.json.
-- Existing rows with matching IDs are updated; related tags and sections for those IDs are rebuilt.

PRAGMA foreign_keys = ON;

-- No task_tags rows to rebuild.
DELETE FROM weekly_report_sections WHERE report_id IN ('weekly-2026-w29');
DELETE FROM weekly_report_tags WHERE report_id IN ('weekly-2026-w29');
DELETE FROM weekly_report_categories WHERE report_id IN ('weekly-2026-w29');

-- No static tasks to seed.

INSERT INTO weekly_reports (
  id,
  week,
  title,
  date_range,
  summary
) VALUES
('weekly-2026-w29', '2026-W29', '研究網站與工具整理週報', '2026-07-13 ~ 2026-07-19', '本週主要完成 Blog 分類與標籤系統，並開始建立任務與週報系統第一版。')
ON CONFLICT(id) DO UPDATE SET
  week = excluded.week,
  title = excluded.title,
  date_range = excluded.date_range,
  summary = excluded.summary,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO weekly_report_sections (
  report_id,
  section_type,
  content,
  sort_order
) VALUES
('weekly-2026-w29', 'completed', '完成文章 category 與 tags 欄位整理', 0),
('weekly-2026-w29', 'completed', '建立 /categories 與 /tags 頁面', 1),
('weekly-2026-w29', 'completed', '在 /blog 加入分類快速篩選', 2),
('weekly-2026-w29', 'progress', '網站逐漸從研究日誌轉向研究管理系統', 0),
('weekly-2026-w29', 'progress', '開始規劃每日任務、每週任務與週報的資料結構', 1),
('weekly-2026-w29', 'problems', '目前任務與週報仍需手動修改 JSON 檔案', 0),
('weekly-2026-w29', 'problems', '尚未加入登入與後台編輯功能', 1),
('weekly-2026-w29', 'solutions', '第一版先使用靜態資料確認版面與資料格式', 0),
('weekly-2026-w29', 'solutions', '等功能穩定後再考慮 Cloudflare D1 或後台編輯', 1),
('weekly-2026-w29', 'unfinished', '任務狀態尚未能在網站上直接編輯', 0),
('weekly-2026-w29', 'unfinished', '週報尚未能自動從任務資料產生', 1),
('weekly-2026-w29', 'next', '測試 /tasks 與 /weekly 頁面', 0),
('weekly-2026-w29', 'next', '思考是否要加入任務篩選功能', 1),
('weekly-2026-w29', 'next', '後續規劃登入與資料庫版本', 2);

INSERT INTO weekly_report_tags (
  report_id,
  tag
) VALUES
('weekly-2026-w29', 'Astro'),
('weekly-2026-w29', '任務管理'),
('weekly-2026-w29', '週報');

INSERT INTO weekly_report_categories (
  report_id,
  category
) VALUES
('weekly-2026-w29', '網站開發'),
('weekly-2026-w29', '研究整理');
