import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = dirname(dirname(fileURLToPath(import.meta.url)));
const tasksPath = join(rootDir, 'src/data/tasks.json');
const reportsPath = join(rootDir, 'src/data/weekly-reports.json');
const seedPath = join(rootDir, 'db/seed.sql');

const taskTypes = new Set(['daily', 'weekly']);
const taskStatuses = new Set(['todo', 'doing', 'done']);
const taskPriorities = new Set(['low', 'medium', 'high']);
const reportSectionTypes = [
	'completed',
	'progress',
	'problems',
	'solutions',
	'unfinished',
	'next',
];

const readJson = (path) => JSON.parse(readFileSync(path, 'utf8'));

const sql = (value) => {
	if (value === null || value === undefined) return 'NULL';
	return `'${String(value).replaceAll("'", "''")}'`;
};

const values = (items) => items.map((item) => `(${item.join(', ')})`).join(',\n');

const validateArray = (value, name) => {
	if (!Array.isArray(value)) {
		throw new Error(`${name} must be an array.`);
	}
	return value;
};

const validateTask = (task) => {
	if (!task.id || !task.title) throw new Error(`Task is missing id or title.`);
	if (!taskTypes.has(task.type)) throw new Error(`Invalid task type: ${task.id}`);
	if (!taskStatuses.has(task.status)) throw new Error(`Invalid task status: ${task.id}`);
	if (!taskPriorities.has(task.priority)) {
		throw new Error(`Invalid task priority: ${task.id}`);
	}
	validateArray(task.tags ?? [], `Task tags for ${task.id}`);
};

const validateReport = (report) => {
	if (!report.id || !report.week || !report.title) {
		throw new Error(`Weekly report is missing id, week, or title.`);
	}

	for (const section of reportSectionTypes) {
		validateArray(report[section] ?? [], `Report ${section} for ${report.id}`);
	}

	validateArray(report.categories ?? [], `Report categories for ${report.id}`);
	validateArray(report.tags ?? [], `Report tags for ${report.id}`);
};

const tasks = readJson(tasksPath);
const reports = readJson(reportsPath);

validateArray(tasks, 'tasks.json').forEach(validateTask);
validateArray(reports, 'weekly-reports.json').forEach(validateReport);

const taskRows = tasks.map((task) => [
	sql(task.id),
	sql(task.title),
	sql(task.description ?? ''),
	sql(task.type),
	sql(task.category ?? '未分類'),
	sql(task.status),
	sql(task.priority),
	sql(task.date ?? null),
	sql(task.week ?? null),
]);

const taskTagRows = tasks.flatMap((task) =>
	(task.tags ?? []).map((tag) => [sql(task.id), sql(tag)]),
);

const reportRows = reports.map((report) => [
	sql(report.id),
	sql(report.week),
	sql(report.title),
	sql(report.dateRange ?? ''),
	sql(report.summary ?? ''),
]);

const reportSectionRows = reports.flatMap((report) =>
	reportSectionTypes.flatMap((sectionType) =>
		(report[sectionType] ?? []).map((content, index) => [
			sql(report.id),
			sql(sectionType),
			sql(content),
			String(index),
		]),
	),
);

const reportTagRows = reports.flatMap((report) =>
	(report.tags ?? []).map((tag) => [sql(report.id), sql(tag)]),
);

const reportCategoryRows = reports.flatMap((report) =>
	(report.categories ?? []).map((category) => [sql(report.id), sql(category)]),
);

const idList = (items) => items.map((item) => sql(item.id)).join(', ');

const insertBlock = (rows, statement, { semicolon = true } = {}) => {
	if (rows.length === 0) return '';
	return `${statement}\n${values(rows)}${semicolon ? ';' : ''}`;
};

const output = `-- Generated by scripts/generate-d1-seed.mjs.
-- This seeds D1 from src/data/tasks.json and src/data/weekly-reports.json.
-- Existing rows with matching IDs are updated; related tags and sections for those IDs are rebuilt.

PRAGMA foreign_keys = ON;

DELETE FROM task_tags WHERE task_id IN (${idList(tasks)});
DELETE FROM weekly_report_sections WHERE report_id IN (${idList(reports)});
DELETE FROM weekly_report_tags WHERE report_id IN (${idList(reports)});
DELETE FROM weekly_report_categories WHERE report_id IN (${idList(reports)});

${insertBlock(
	taskRows,
	`INSERT INTO tasks (
  id,
  title,
  description,
  type,
  category,
  status,
  priority,
  task_date,
  week
) VALUES`,
	{ semicolon: false },
)}
ON CONFLICT(id) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  type = excluded.type,
  category = excluded.category,
  status = excluded.status,
  priority = excluded.priority,
  task_date = excluded.task_date,
  week = excluded.week,
  updated_at = CURRENT_TIMESTAMP;

${insertBlock(
	taskTagRows,
	`INSERT INTO task_tags (
  task_id,
  tag
) VALUES`,
)}

${insertBlock(
	reportRows,
	`INSERT INTO weekly_reports (
  id,
  week,
  title,
  date_range,
  summary
) VALUES`,
	{ semicolon: false },
)}
ON CONFLICT(id) DO UPDATE SET
  week = excluded.week,
  title = excluded.title,
  date_range = excluded.date_range,
  summary = excluded.summary,
  updated_at = CURRENT_TIMESTAMP;

${insertBlock(
	reportSectionRows,
	`INSERT INTO weekly_report_sections (
  report_id,
  section_type,
  content,
  sort_order
) VALUES`,
)}

${insertBlock(
	reportTagRows,
	`INSERT INTO weekly_report_tags (
  report_id,
  tag
) VALUES`,
)}

${insertBlock(
	reportCategoryRows,
	`INSERT INTO weekly_report_categories (
  report_id,
  category
) VALUES`,
)}
`;

writeFileSync(seedPath, output.replace(/\n{3,}/g, '\n\n'));
console.log(`Generated ${seedPath}`);
